# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from application.grpc_server.proto_buf import BarraRpcService_pb2 as proto_dot_BarraRpcService__pb2


class BarraRpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Barra = channel.unary_stream(
                '/com.ncamc.rps.common.grpc.example.BarraRpcService/Barra',
                request_serializer=proto_dot_BarraRpcService__pb2.BarraRequest.SerializeToString,
                response_deserializer=proto_dot_BarraRpcService__pb2.BarraResponse.FromString,
                )


class BarraRpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Barra(self, request, context):
        """单向流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarraRpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Barra': grpc.unary_stream_rpc_method_handler(
                    servicer.Barra,
                    request_deserializer=proto_dot_BarraRpcService__pb2.BarraRequest.FromString,
                    response_serializer=proto_dot_BarraRpcService__pb2.BarraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.ncamc.rps.common.grpc.example.BarraRpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BarraRpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Barra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.ncamc.rps.common.grpc.example.BarraRpcService/Barra',
            proto_dot_BarraRpcService__pb2.BarraRequest.SerializeToString,
            proto_dot_BarraRpcService__pb2.BarraResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
