# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/BarraRpcService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/BarraRpcService.proto\x12!com.ncamc.rps.common.grpc.example\"*\n\x0c\x42\x61rraRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\t\".\n\rBarraResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x0f\x42\x61rraRpcService\x12n\n\x05\x42\x61rra\x12/.com.ncamc.rps.common.grpc.example.BarraRequest\x1a\x30.com.ncamc.rps.common.grpc.example.BarraResponse\"\x00\x30\x01\x42\x39\n%com.ncamc.rps.common.grpc.example.libB\x0e\x42\x61rraCalcProtoP\x01\x62\x06proto3')



_BARRAREQUEST = DESCRIPTOR.message_types_by_name['BarraRequest']
_BARRARESPONSE = DESCRIPTOR.message_types_by_name['BarraResponse']
BarraRequest = _reflection.GeneratedProtocolMessageType('BarraRequest', (_message.Message,), {
  'DESCRIPTOR' : _BARRAREQUEST,
  '__module__' : 'proto.BarraRpcService_pb2'
  # @@protoc_insertion_point(class_scope:com.ncamc.rps.common.grpc.example.BarraRequest)
  })
_sym_db.RegisterMessage(BarraRequest)

BarraResponse = _reflection.GeneratedProtocolMessageType('BarraResponse', (_message.Message,), {
  'DESCRIPTOR' : _BARRARESPONSE,
  '__module__' : 'proto.BarraRpcService_pb2'
  # @@protoc_insertion_point(class_scope:com.ncamc.rps.common.grpc.example.BarraResponse)
  })
_sym_db.RegisterMessage(BarraResponse)

_BARRARPCSERVICE = DESCRIPTOR.services_by_name['BarraRpcService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%com.ncamc.rps.common.grpc.example.libB\016BarraCalcProtoP\001'
  _BARRAREQUEST._serialized_start=66
  _BARRAREQUEST._serialized_end=108
  _BARRARESPONSE._serialized_start=110
  _BARRARESPONSE._serialized_end=156
  _BARRARPCSERVICE._serialized_start=159
  _BARRARPCSERVICE._serialized_end=288
# @@protoc_insertion_point(module_scope)
